// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGUTo5sHx9tKfpB1j6H6Lcy20APCHBsiE',
    appId: '1:521464614719:web:95fca648cb1a78167a8d8a',
    messagingSenderId: '521464614719',
    projectId: 'flutterfirebase-9ecc0',
    authDomain: 'flutterfirebase-9ecc0.firebaseapp.com',
    storageBucket: 'flutterfirebase-9ecc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCds1HyrDZOulGGJsqRhSLM3Q4w389oMgI',
    appId: '1:521464614719:android:6725b8f1138d9a1d7a8d8a',
    messagingSenderId: '521464614719',
    projectId: 'flutterfirebase-9ecc0',
    storageBucket: 'flutterfirebase-9ecc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCei96kO7MTrjKvS-7zhawpFnmhxqv-Gk8',
    appId: '1:521464614719:ios:5d74a39e803af6837a8d8a',
    messagingSenderId: '521464614719',
    projectId: 'flutterfirebase-9ecc0',
    storageBucket: 'flutterfirebase-9ecc0.appspot.com',
    iosBundleId: 'com.example.myfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCei96kO7MTrjKvS-7zhawpFnmhxqv-Gk8',
    appId: '1:521464614719:ios:5d74a39e803af6837a8d8a',
    messagingSenderId: '521464614719',
    projectId: 'flutterfirebase-9ecc0',
    storageBucket: 'flutterfirebase-9ecc0.appspot.com',
    iosBundleId: 'com.example.myfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGUTo5sHx9tKfpB1j6H6Lcy20APCHBsiE',
    appId: '1:521464614719:web:ef1c0fbeff7357297a8d8a',
    messagingSenderId: '521464614719',
    projectId: 'flutterfirebase-9ecc0',
    authDomain: 'flutterfirebase-9ecc0.firebaseapp.com',
    storageBucket: 'flutterfirebase-9ecc0.appspot.com',
  );
}
